### ISSUE TITLE
adding a chart

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/dashboard-builder#12]
scenario:
1. I drag a new chart from the left nav to the content area.
2. new chart is created
3. before I do anything with the chart - I want to move it, resize etc
4. now when I got position and size right - I want to select saved query

Problem is that when I start moving the chart - it loses "focus" (the right column is showing only general project options).

Solution (if it's possible to implement)
onMouseDown on the chart element - set some kind of focus on it. This way if I resize it or change position of it, I'll be still able to chose a different saved query in the right column.

**Comment by dariuszlacheta** [comment]
Right now if any element(new one or existing one) is mark as active(settings for this chart are visible), moving and resizing will not lose focus.
