### ISSUE TITLE
dashboard viewer react component

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/dashboard-builder#126]
just like embed html, but for React
ability to add a dashboard viewer to a react app. It's possible now, but we can make it easier by preparing custom component.

sample code (just for general overview):
```javascript
import DashboardViewer from 'keen-dashboard-builder/lib/viewer/component';

const App123 = props => {
  return (
    <DashboardViewer
       projectId='123'
       accessKey='000'
    />
  );
}
```

**Comment by jamesaharvey** [comment]
How is it possible to do this with the above sample code?  I'm trying to incorporate a DashboardViewer into a sample react app, but am not having any luck.  I'm also using TypeScript, so a typings file would also be most helpful.

**Comment by apryka** [comment]
react component hasn't been released yet but you can try with https://jsfiddle.net/s8r7mt6x/

support for typescript is in our backlog and will be added in the future

**Comment by apryka** [comment]
react component has been released -> https://github.com/keen/react-public-dashboard
