### ISSUE TITLE
saving dashboards

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/dashboard-builder#32]
let's change the names of json properties:

```js
{
  title: 'some dash 123', // title of dashboard, that was previously called "dashboardTitle"
  projectId: '12345', // just like in the old dashboards
  rows: [], // just to pass the backend validation

  data: { // this field is new and optional
    version: 2, // version of the dashboard builder json
    items: [ // array of elements, that was previously called "dashboardData"
      {
         // ... props of each element/chart
      }
    ],
  },

  settings: { // this field is new and optional
    dryRun: false,  // optional
    colors: [], // optional
    palette: {} // optional
  }
}
```

Note:
- new fields in this JSON are optional, because some of our customers will still use the old version of dashboard builder
- let's put all of the charts in the data.items field
- let's put all of the general dashboard settings in the settings field

Validation:
- if the JSON has a property called `data`, it should also have `data.version` and `data.items`
- `data.version` should be an Integer
- `data.items` should be an array of objects. The minimum number of items in this array is 0
- `settings` - don't validate this field yet
- `data` and `settings` are optional, because some of our users will still use the old dashboards

**Comment by dariuszlacheta** [comment]
It was implemented pushed to dlacheta-dashboard-builder branch, also deployed on github-pages; Please go to: https://keen.github.io/dashboard-builder/#/
Clear You local storage for that website and verify if structure is the same as it is above.

**Comment by adamkasprowicz** [comment]
look fine, but `data.version` is missing. It defines version of the schema that we can expect from data.items.
Let's start with data.version = 2.

**Comment by dariuszlacheta** [comment]
`data.version = 2` added

**Comment by adamkasprowicz** [comment]
I've reopened since the builder is still saving into the localStorage, not into the API
