### ISSUE TITLE
UX - clicking on a chart element

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/dashboard-builder#51]
scenario:
1. user has a dashboard with some charts
2. user clicks on a chart
3. it doesn't do anything

desired behaviour:
3. it selects this chart and renders settings of this chart in the right column

**Comment by adamkasprowicz** [comment]
sometimes it works, sometimes it doesn't.
If the problem is because of the dragging feature, we can reduce the dragpoint to just a small icon

**Comment by dariuszlacheta** [comment]
It is a small problem because of dragging feature, but I was able to improve it, please check now, should works smooth now.

**Comment by adamkasprowicz** [comment]
now it works great 👍
