### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by dariuszlacheta** [keen/dashboard-builder#7]
We need to start working on API endpoint. We can use the old one - but we need to introduce the new field into
https://github.com/keenlabs/Keen-Web/blob/774ebdb97b507a92c7ade7011f10c412c66cc656/app/models/dashboard.py
the field will contain the whole JSON that the builder produces

**Comment by adamkasprowicz** [comment]
let's move our conversations into 
https://github.com/keen/dashboard-builder/issues/32
